configfile: "config/config.yaml"


container: "docker://condaforge/mambaforge:{{cookiecutter.mambaforge}}"


report: "report/workflow.rst"


include: "rules/common.smk"
include: "rules/analysis.smk"


rule report:
    input:
        # The first rule should define the default target files
