$schema: "http://json-schema.org/draft-07/schema#"

description: Config File Schema

properties:
  samples:
    description: Samplesheet location
    type: string

additionalProperties: false
required:
  - samples
